### ISSUE TITLE
Alt text attribute duplicates section title when section image is set (accessibility)

### ISSUE THREAD

**Issue by logan-reynolds** [gjbarnard/moodle-format_grid#108]
When an image is set for a given section, that image's alt text is automatically set to be the same as the section name.  This is repetitive and doesn't really satisfy the accessibility requirements for alt text since a screenreader will just read the same text twice. A better solution would be to allow the user to write alt text for each image and if it's blank, leave the alt text as null.

**Comment by gjb2048** [comment]
Thanks for the suggestion @logan-reynolds, please feel free to submit a patch with the solution.

**Comment by gjb2048** [comment]
@logan-reynolds Or if you'd like to fund the enhancement, I'm open to proceeding with the admin needed.

**Comment by logan-reynolds** [comment]
Hello; I've submitted pull requests# 110-116 for all branches to add the alt text functionality, noting the reason we are requesting this be ported back as far as Moodle 3.2 is because this is the minimum version we need to work on Totara 12 which is what our requesting client is going to utilize grid format on.  Please let me know if anything further is needed; thank you.

**Comment by gjb2048** [comment]
Dear @logan-reynolds,

Thanks for the patches, that's a shed load of work for me as M3.6- versions will also need updating so that they are consistent with the functionality in 'master' which is M3.8 - probably.  Therefore I'm willing to review and accept the two M3.7+ branches, but as its for a 'client' then will need my time funded for all versions below that.  Plus my environment only goes down to M3.5 so I'd need time, chargeable, to set-up a virtual machine to test M3.4- on too.

G

**Comment by gjb2048** [comment]
Funding not forthcoming, closing.
