### ISSUE TITLE
Course sections outside the "Number of sections" setting are not able to use the "Hidden & Make Available" options.

### ISSUE THREAD

**Issue by Syxton** [gjbarnard/moodle-format_grid#196]
**Describe the bug**
"Make Available" is not possible in course sections of a higher number than the course sections that are actually in the course.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a course with 10 sections.
2. Make an activity in the 10th section.
3. Change the course format "Number of sections" to less than 10.
4. Hide the activity in section 10.
5. Attempt to make the activity "Available"

**Expected behaviour**
All course options are still available for all activities in the course.

**Screenshots**

**Versions (please complete the following information):**
 - Moodle: 402.2.1b

**Additional context**
The expected behavior of changing the "Number of sections" is to add more sections or "remove empty / orphan" sections.

**Comment by gjb2048** [comment]
@Syxton

When was it ever possible to do so in an orphaned section?

"The expected behavior of changing the "Number of sections" is to add more sections or "remove empty / orphan" sections." = no, it works that way already, only removing sections if they don't contain content.  If there is content in a section that is greater than the number of sections then that section needs to be an orphan.

**Comment by gjb2048** [comment]
Note: M4.3 seems to have removed the "Hidden & Make Available" option.

**Comment by gjb2048** [comment]
@Syxton Course formats have no control / ability to change module code.
